#!/usr/bin/env bash
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

feh --bg-scale ~/Wallpaper

$HOME/.config/polybar/launch.sh
#panel & disown

# restart dunst
killall -q dunst
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
dunst &

#CURSOR_NAME=$(cat $HOME/.gtkrc-2.0 | awk -F "=" '/gtk-cursor-theme-name/ {print $2}' | sed s/\"//g)
#echo $CURSOR_NAME | dmenu
xsetroot -cursor_name left_ptr
xrdb $HOME/.Xresources
notify-send -t 3000 "BSPWM loaded"

