#!/usr/bin/env sh
feh --bg-scale $HOME/Wallpaper
dunst &
compton &
sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
#panel & disown

setroot -cursor_name left_ptr
xrdb $HOME/.Xresources
notify-send -t 3000 "BSPWM loaded"

