#!/usr/bin/env python3
import os
import re

I3_CONF_PATH = os.path.expanduser('~/.config/i3/config')
BASHRC_PATH = os.path.expanduser('~/.bashrc')


def main():
    # Get i3 shortcuts.
    print('i3\n---------------')
    for line in open(I3_CONF_PATH):
        if line.startswith('bindsym'):
            words = line.strip().split(' ')[1:]
            print('%-25s%s' % (words[0], ' '.join(words[1:])))

    print('\nbash\n---------------')
    for line in open(BASHRC_PATH):
        if line.startswith('alias'):
            # Remove quotes and line endings, then transform equals signs into spaces
            words = re.sub('[=]', ' ', re.sub('[\"\n]', '', line)).split(' ')[1:]
            print('%-25s%s' % (words[0], ' '.join(words[1:])))


if __name__ == '__main__':
    main()
